version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    env_file: .env
    build: ./web
    container_name: "wine_reviews_web"
    command: ./entrypoint.sh
    volumes:
      - ./web:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
