"""removed names unique contraint

Revision ID: 42c1b5715612
Revises: bc9760e3cc72
Create Date: 2018-12-11 12:19:56.206464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c1b5715612'
down_revision = 'bc9760e3cc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_name', table_name='cities')
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index('ix_cities_name', 'cities', ['name'], unique=True)
    # ### end Alembic commands ###
